parser: babel-eslint
env:
  es6: true
  browser: true
  node: true
extends:
  - eslint:recommended
  - google
rules:
  indent:
    - error
    - 2
    - MemberExpression: 1
  semi: off
  max-len:
    - error
    - code: 120
  object-curly-spacing: off
  require-jsdoc: off
